# Generated by Django 2.0.6 on 2018-07-07 14:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(max_length=20)),
                ('blogPost', models.CharField(default=models.CharField(max_length=20), max_length=1000)),
                ('commentid', models.CharField(blank=True, max_length=100)),
                ('commentCount', models.IntegerField(blank=True, default=0)),
                ('likesCount', models.IntegerField(blank=True, default=0)),
                ('likedUsers', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='commentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bloggingApp.blogInfo'), max_length=150)),
                ('blogid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bloggingApp.blogInfo')),
            ],
        ),
        migrations.CreateModel(
            name='profileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(blank=True, default='no_name', max_length=25)),
                ('firstname', models.CharField(blank=True, max_length=25, null=True)),
                ('lastname', models.CharField(blank=True, max_length=25, null=True)),
                ('profilepic', models.ImageField(blank=True, default='', upload_to='uploads/')),
                ('followers', models.CharField(blank=True, max_length=100, null=True)),
                ('following', models.CharField(blank=True, max_length=100, null=True)),
                ('followersCount', models.IntegerField(default=0)),
                ('followingCount', models.IntegerField(default=0)),
                ('blogs', models.CharField(blank=True, max_length=100, null=True)),
                ('blogCount', models.IntegerField(default=0)),
                ('dateOfBirth', models.DateField(default=datetime.date.today)),
                ('mobileno', models.CharField(blank=True, max_length=10, null=True)),
                ('userid', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='userinfo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bloggingApp.profileInfo'),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='userinfo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bloggingApp.profileInfo'),
        ),
    ]
