# Generated by Django 2.0.6 on 2018-07-07 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='userid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
