# Generated by Django 2.0.6 on 2018-07-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingApp', '0003_auto_20180707_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='profilepic',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
    ]
