# Generated by Django 2.0.6 on 2018-07-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingApp', '0004_auto_20180719_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='profilepic',
            field=models.FileField(blank=True, default='', upload_to='media/'),
        ),
    ]
