# Generated by Django 2.0.6 on 2018-07-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingApp', '0005_auto_20180719_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='gender',
            field=models.CharField(blank=True, default='male', max_length=7),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='profilepic',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
